### ISSUE TITLE
Mac version of cosmic-app-template?

### ISSUE THREAD

**Issue by yoggiland** [pop-os/cosmic-app-template#2]
Hi,

I'm new to programming, new to Rust and new to libcosmic.

I know that libcosmic primary use is for Pop OS (and I do run Pop! OS 24.04 COSMIC Alpha on my Proxmox machine) but my primary machine is a Macbook Pro 2016 and I would like to use it natively to learn and create Cosmic applications.

I have manage to compile some libcosmic demos and small programs but the learning curve was a bit steep.

I can't get the cosmic-app-template to build. I appears that the  cosmic-app-template requires Wayland (which is not available on Mac). Yes I understand Pop OS  is Linux (Wayland) but as I understand libcosmic aims to be cross platform and there for it would be nice to have a templet that works on other platforms then Linux.

I think I'm over the main hurdle that prevented me from learning libcosmic on the Mac but I'm guessing there are other new beginners out there that would like to get started with libcosmic.

**Comment by mmstick** [comment]
Wayland shouldn't be required if the winit feature is being used.

**Comment by yoggiland** [comment]
Hi mmstick,

Not sure what changed... I just cloned (started fresh again) the cosmic-app-template repository (git clone https://github.com/pop-os/cosmic-app-template.git) and I ran the just script ('just run') and it built and compiled without error and ran the "cosmic-app-template" application.

I can also re run the application (found in `target/release/cosmic-app-template`) and it works fine.

As I said, not sure what was the problem was before but the Cosmic templet compiles fine in VS Code on my old Intel Mac!

yoggi

**Comment by DataM0del** [comment]
> Hi mmstick,
> 
> Not sure what changed... I just cloned (started fresh again) the cosmic-app-template repository (git clone https://github.com/pop-os/cosmic-app-template.git) and I ran the just script ('just run') and it built and compiled without error and ran the "cosmic-app-template" application.
> 
> I can also re run the application (found in `target/release/cosmic-app-template`) and it works fine.
> 
> As I said, not sure what was the problem was before but the Cosmic templet compiles fine in VS Code on my old Intel Mac!
> 
> yoggi

Do you know if it works on the new Apple M series chips? the main difference is that they use ARM instead of x64 / x86

**Comment by yoggiland** [comment]
@DataM0del 

Sorry I don't know as I don't have a Mac with Apple silicon to try on (just an old Intel Macbook Pro)
