### ISSUE TITLE
Remove `Cargo.lock`

### ISSUE THREAD

**Issue by bbb651** [pop-os/cosmic-app-template#3]
I've just spent a lot of time trying to debug panics I was getting on `text_input`, only to realize libcosmic was locked to [this commit](https://github.com/pop-os/libcosmic/commit/16c1265535a0a4d9e1e5ded2f39096dc8f144e9c) from May, because of [the way cargo git dependencies work](https://github.com/rust-lang/cargo/commit/21a1e1544b6ca41921ed53b228f1241665a4dcd6) (not sure why this seems to have been removed from the docs). This is also true for other crates not being up to date in `Cargo.toml` but it's less critical, since they change way less frequently.

Removing `Cargo.lock` seems like a good idea to me, it seems unnecessary for a template. In either case I can also make a PR updating all dependencies. I've also looked at [cargo-generate](https://github.com/cargo-generate/cargo-generate) like it would make setting up the template a lot quicker.

**Comment by mmstick** [comment]
That would be fine.
